version: '3.4'
services:
   db:
      image: mysql:5.7.22
      command: mysqld --default_authentication_plugin=mysql_native_password
      environment:
         TZ: America/Sao_Paulo
         MYSQL_ROOT_PASSWORD: docker
         MYSQL_USER: docker
         MYSQL_PASSWORD: docker
         MYSQL_DATABASE: wordpress
      ports:
         - 3308:3306
      networks:
         - wordpress-network
   wordpress:
      image: wordpress:latest
      volumes:
         - ./config/php.conf.uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
         - ./wp-app:/var/www/html
      environment:
         TZ: America/Sao_Paulo
         WORDPRESS_DB_HOST: db
         WORDPRESS_DB_NAME: wordpress
         WORDPRESS_DB_USER: root
         WORDPRESS_DB_PASSWORD: docker
      ports:
         - 80:80
      networks:
         - wordpress-network
networks:
   wordpress-network:
      driver: bridge
# código abaixo dando erro
# version: '3.3'
# services:
#    db: #container de MySQL
#       image: mysql:5.7 #FROM mysql:5.7
#       volumes:
#          - db_data:/var/lib/mysql
#       restart: always
#       environment:
#          MYSQL_ROOT_PASSWORD: wordpress
#          MYSQL_DATABASE: wordpress
#          MYSQL_USER: leonardo
#          MYSQL_PASSWORD: l1j1o1s1
#    wordpress: #aplicacao web
#       depends_on:
#          - db
#       image: wordpress:latest
#       ports:
#          - '8000:80'
#       restart: always
#       environment:
#          WORDPRESS_DB_HOST: db:3306
#          WORDPRESS_DB_USER: leonardo
#          WORDPRESS_DB_PASSWORD: l1j1o1s1
#          WORDPRESS_DB_NAME: wordpress
# volumes:
#    db_data: {}
